stages:
  - linting
  - test

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - flake8 --verbose .
  allow_failure: true

build:
  when: manual
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker version
    - docker-compose version
  stage: test
  script:
    - docker-compose up -d --build
    - docker exec -it python_django_team14-web python manage.py test
