stages:
  - linting
  - test

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - flake8 --verbose .
  allow_failure: true

build:
  when: manual
  image: docker:20.10.16
  services:
    - name:docker:20.10.16-dind
        - alias: thedockerhost
  variables:
    DOCKER_HOST: tcp://thedockerhost:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker info
    - docker-compose info
  stage: test
  script:
    - docker-compose up -d --build
    - docker exec -it python_django_team14-web python manage.py test
